// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAotPSoFZMoZUNhVxHDJezp035F1tumm2c',
    appId: '1:567112936187:web:f8474d5f13464d00231e5e',
    messagingSenderId: '567112936187',
    projectId: 'livekick-c2d11',
    authDomain: 'livekick-c2d11.firebaseapp.com',
    storageBucket: 'livekick-c2d11.firebasestorage.app',
    measurementId: 'G-81780T2SX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyJ8P5BqgqFS7TdtvNJ07kk6LFaS2iQ84',
    appId: '1:567112936187:android:469d3f0d81ac0dab231e5e',
    messagingSenderId: '567112936187',
    projectId: 'livekick-c2d11',
    storageBucket: 'livekick-c2d11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdEyuoIkEV06zmHf_AQKBvtybXu32V7Bg',
    appId: '1:567112936187:ios:801b39c745c0c9c9231e5e',
    messagingSenderId: '567112936187',
    projectId: 'livekick-c2d11',
    storageBucket: 'livekick-c2d11.firebasestorage.app',
    iosBundleId: 'com.example.livekick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdEyuoIkEV06zmHf_AQKBvtybXu32V7Bg',
    appId: '1:567112936187:ios:801b39c745c0c9c9231e5e',
    messagingSenderId: '567112936187',
    projectId: 'livekick-c2d11',
    storageBucket: 'livekick-c2d11.firebasestorage.app',
    iosBundleId: 'com.example.livekick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAotPSoFZMoZUNhVxHDJezp035F1tumm2c',
    appId: '1:567112936187:web:2671f79fd05dd701231e5e',
    messagingSenderId: '567112936187',
    projectId: 'livekick-c2d11',
    authDomain: 'livekick-c2d11.firebaseapp.com',
    storageBucket: 'livekick-c2d11.firebasestorage.app',
    measurementId: 'G-VSF76L3WC1',
  );
}
